### ISSUE TITLE
PGSoftwareSolutions.pfx is password protected.

### ISSUE THREAD

**Issue by asusralis** [pgeerkens/HexGridUtilitiesForGames#4]
I'm sorry if I missed something, but is this intended?

**Comment by pgeerkens** [comment]
Yes; that is so no-one else signs as me. Just delete it and create your own credential file to sign with.  
Note that I messed up branching with TFS while this project was in CodePlex, so some clean-up may be necessary. I hope to get to that this weekend.

**Comment by asusralis** [comment]
I see! I fixed the signing problem, but I have (23) errors about missing source files, so I'll wait a few days. :)

I'm really excited on seeing your library being moved to Github! C# is surprising missing a hexagon utility library that isn't coupled to a specific environment like Unity.
