### ISSUE TITLE
Files missing from version control

### ISSUE THREAD

**Issue by primitiveType** [pgeerkens/HexGridUtilitiesForGames#5]
attempting to clone and build the project results in many errors, most importantly issues with missing files.
Severity	Code	Description	Project	File	Line	Suppression State
UseHexGridUtilities\HexUtilities\Common\BlockedBoardStorage32x32.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Common\FlatBoardStorage.cs' could not be found.	
UseHexGridUtilities\HexUtilities\IHex.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Common\BoardStorage.cs' could not be found.	
UseHexGridUtilities\HexUtilities\IHexBoard.cs' could not be found.	
UseHexGridUtilities\HexUtilities\IHexgrid.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Pathfinding\IDirectedPathCollection.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Pathfinding\ILandmark.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Pathfinding\INavigableBoard.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Pathfinding\IPathfinder.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Hexsides.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Common\EnumHelper.cs' could not be found.	
UseHexGridUtilities\HexUtilities\Common\IBoardStorage.cs' could not be found.	
UseHexGridUtilities\HexUtilities\FieldOfView\IFieldOfView.cs' could not be found.	
UseHexGridUtilities\HexgridPanel\BufferedHexgridScrollable.cs' could not be found.	
UseHexGridUtilities\HexgridPanel\BufferedHexgridScrollable.Designer.cs' could not be found.	
UseHexGridUtilities\HexgridPanel\bin\Debug\HexgridPanel.dll' could not be found	
UseHexGridUtilities\HexUtilities\bin\Debug\PGNapoleonics.HexUtilities.dll' could not be found	
UseHexGridUtilities\HexUtilities\bin\Debug\PGNapoleonics.HexUtilities.dll' could not be found	
UseHexGridUtilities\HexGridExampleCommon\bin\Debug\HexgridExampleCommon.dll' could not be found	
UseHexGridUtilities\HexgridPanel\bin\Debug\HexgridPanel.dll' could not be found	
UseHexGridUtilities\HexUtilities\bin\Debug\PGNapoleonics.HexUtilities.dll' could not be found	

These files don't seem to exist in the repo structure

**Comment by primitiveType** [comment]
These files aren't missing from version control, they have just been moved and the solution file isn't up-to-date.

**Comment by pgeerkens** [comment]
> These files aren't missing from version control, they have just been moved and the solution file isn't up-to-date.

My apologies for the very long delay getting to this. The branch **master** is no repaired, and I am working on restoring the documentation through Doxygen.
