### ISSUE TITLE
This code drop is unusable

### ISSUE THREAD

**Issue by david-pfx** [pgeerkens/HexGridUtilitiesForGames#7]
This project does not even come close to building. There are multiple files that have been moved, renamed, modified, merged, missing. Some files are duplicated with two different versions; others are missing entirely; many files are not where the projects can find them. I tried, but I failed.

Please fix it at least so the checkout builds. Remove the strong key stuff, do some basic testing.

Otherwise it's just a pile of junk.

**Comment by pgeerkens** [comment]
### Diagnosis:
- When ported from **CodePlex** the branching got messed up.

### Remedy:
- Basic structure of the library has been fixed
- All three technology examples build and run
- Mapping, CoordinatePicking, PathFinding and FieldOfView all appear to be working fine.
- Strong key stuff removed
- The (no longer supported) MS CodeContracts library use has been removed

### Remaining work:
- Doxygen docgeneration needs to be restored
- the ReadMe needs to be reassembled

### Notes
- Original code now squirreled away on **codeplex** branch in **codeplex** folder.
- Everything else (I believe) is current.

**Comment by pgeerkens** [comment]
### Addenda
- Strong key stuff removed

**Comment by pgeerkens** [comment]
> This project does not even come close to building. There are multiple files that have been moved, renamed, modified, merged, missing. Some files are duplicated with two different versions; others are missing entirely; many files are not where the projects can find them. I tried, but I failed.
> 
> Please fix it at least so the checkout builds. Remove the strong key stuff, do some basic testing.
> 
> Otherwise it's just a pile of junk.

The branch **master** should now compile and run all three technology examples. I am working on restoring the Doxygen auto-generated documentation. Let me know if you encounter any further issues.
